services:
  - type: web
    name: attendify-app
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    disk:
      name: attendance-mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 5
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_DATABASE
        value: attendance_system
      - key: MYSQL_USER
        value: attendance
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
