import { formatMoney } from "./format";
import type { PayrollSummary } from "../types";

export function downloadPayrollCsv(payroll: PayrollSummary) {
  const header = [
    "Employee",
    "Designation",
    "Status",
    "Monthly Salary",
    "Days Counted",
    "Worked Days",
    "Half Days",
    "Holiday Days",
    "Worked Day Units",
    "Allowed Leaves",
    "Paid Leaves Used",
    "Unpaid Leaves",
    "Payable Days",
    "Daily Rate",
    "Gross Payable",
    "Opening Advance",
    "Month Advance Paid",
    "Total Advance Deducted",
    "Net Payable"
  ];

  const rows = payroll.employees.map((employee) => [
    employee.employeeName,
    employee.designation,
    employee.status,
    employee.monthlySalary.value,
    employee.daysCounted,
    employee.workedDays,
    employee.halfDays,
    employee.holidayDays,
    employee.workedDayUnits.value,
    employee.allowedLeaves,
    employee.paidLeaveDays,
    employee.unpaidLeaveDays,
    employee.payableDays.value,
    employee.dailyRate.value,
    employee.grossPayable.value,
    employee.openingAdvance.value,
    employee.monthAdvancePaid.value,
    employee.totalAdvanceDeducted.value,
    employee.netPayable.value
  ]);

  const csv = [header, ...rows]
    .map((row) => row.map((cell) => `"${String(cell ?? "").replace(/"/g, '""')}"`).join(","))
    .join("\n");

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `attendify-payroll-${payroll.month}.csv`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function downloadSalarySlip(payroll: PayrollSummary, employeeId: string) {
  const employee = payroll.employees.find((entry) => entry.employeeId === employeeId);
  if (!employee) {
    return;
  }

  const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>ATTENDIFY Salary Slip - ${employee.employeeName}</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 32px; color: #0f172a; }
      h1 { margin-bottom: 4px; color: #1d4ed8; }
      h2 { margin-top: 0; font-size: 18px; color: #475569; }
      table { width: 100%; border-collapse: collapse; margin-top: 24px; }
      th, td { padding: 10px 12px; border: 1px solid #cbd5e1; text-align: left; }
      th { background: #eff6ff; }
      .summary { margin-top: 16px; font-size: 15px; }
    </style>
  </head>
  <body>
    <h1>ATTENDIFY Salary Slip</h1>
    <h2>${employee.employeeName} · ${employee.designation} · ${payroll.month}</h2>
    <table>
      <tr><th>Monthly salary</th><td>${formatMoney(employee.monthlySalary.value)}</td></tr>
      <tr><th>Worked days</th><td>${employee.workedDays}</td></tr>
      <tr><th>Half days</th><td>${employee.halfDays}</td></tr>
      <tr><th>Holiday days</th><td>${employee.holidayDays}</td></tr>
      <tr><th>Worked day units</th><td>${employee.workedDayUnits.value}</td></tr>
      <tr><th>Paid leave used</th><td>${employee.paidLeaveDays}</td></tr>
      <tr><th>Unpaid leaves</th><td>${employee.unpaidLeaveDays}</td></tr>
      <tr><th>Payable days</th><td>${employee.payableDays.value}</td></tr>
      <tr><th>Daily rate</th><td>${formatMoney(employee.dailyRate.value)}</td></tr>
      <tr><th>Gross payable</th><td>${formatMoney(employee.grossPayable.value)}</td></tr>
      <tr><th>Opening advance</th><td>${formatMoney(employee.openingAdvance.value)}</td></tr>
      <tr><th>Month advance paid</th><td>${formatMoney(employee.monthAdvancePaid.value)}</td></tr>
      <tr><th>Total advance deducted</th><td>${formatMoney(employee.totalAdvanceDeducted.value)}</td></tr>
      <tr><th>Net payable</th><td><strong>${formatMoney(employee.netPayable.value)}</strong></td></tr>
    </table>
    <div class="summary">Generated by ATTENDIFY payroll.</div>
  </body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `attendify-salary-slip-${employee.employeeName.replace(/\s+/g, "-").toLowerCase()}-${payroll.month}.html`;
  anchor.click();
  URL.revokeObjectURL(url);
}
