import { formatDateTime, formatMoney } from "./format";
import type { SubscriptionDashboard, SubscriptionPaymentHistoryEntry } from "../types";

export function downloadSubscriptionInvoice(
  dashboard: SubscriptionDashboard,
  payment: SubscriptionPaymentHistoryEntry
) {
  const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>PEEPLIFY Invoice - ${payment.cashfreeOrderId ?? payment.checkoutSessionId}</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 32px; color: #0f172a; }
      h1 { margin-bottom: 4px; color: #1d4ed8; }
      h2 { margin-top: 0; font-size: 18px; color: #475569; }
      table { width: 100%; border-collapse: collapse; margin-top: 24px; }
      th, td { padding: 10px 12px; border: 1px solid #cbd5e1; text-align: left; }
      th { background: #eff6ff; width: 32%; }
      .meta { margin-top: 16px; font-size: 15px; color: #475569; }
    </style>
  </head>
  <body>
    <h1>PEEPLIFY Invoice</h1>
    <h2>${dashboard.currentPlan.vendorName}</h2>
    <div class="meta">Property code: ${dashboard.currentPlan.propertyCode}</div>
    <table>
      <tr><th>Invoice reference</th><td>${payment.cashfreeOrderId ?? payment.checkoutSessionId}</td></tr>
      <tr><th>Plan</th><td>${payment.planLabel}</td></tr>
      <tr><th>Billing cycle</th><td>${payment.billingCycle}</td></tr>
      <tr><th>Employees included</th><td>${payment.employeeLimit ?? "Custom"}</td></tr>
      <tr><th>Branches included</th><td>${payment.branchLimit}</td></tr>
      <tr><th>Access type</th><td>${payment.accessMode}</td></tr>
      <tr><th>Amount paid</th><td><strong>${formatMoney(payment.amount)}</strong></td></tr>
      <tr><th>Payment status</th><td>${payment.paymentStatus ?? "Pending"}</td></tr>
      <tr><th>Created at</th><td>${formatDateTime(payment.createdAt)}</td></tr>
      <tr><th>Verified at</th><td>${formatDateTime(payment.verifiedAt)}</td></tr>
      <tr><th>Access valid until</th><td>${formatDateTime(payment.accessExpiresAt)}</td></tr>
    </table>
    <div class="meta">Generated by PEEPLIFY subscription billing.</div>
  </body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `peeplify-invoice-${(payment.cashfreeOrderId ?? payment.checkoutSessionId).toLowerCase()}.html`;
  anchor.click();
  URL.revokeObjectURL(url);
}
