import { formatDateTime, formatMoney } from "./format";
import type { SubscriptionDashboard, SubscriptionPaymentHistoryEntry } from "../types";

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function buildSimplePdf(lines: string[]) {
  const pageWidth = 595;
  const pageHeight = 842;
  const startY = 790;
  const lineHeight = 20;
  const content = [
    "BT",
    "/F1 16 Tf",
    `50 ${startY} Td`
  ];

  lines.forEach((line, index) => {
    if (index === 0) {
      content.push(`(${escapePdfText(line)}) Tj`);
      return;
    }
    content.push(`0 -${lineHeight} Td`);
    content.push(`(${escapePdfText(line)}) Tj`);
  });

  content.push("ET");
  const stream = content.join("\n");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return pdf;
}

export function downloadSubscriptionInvoice(
  dashboard: SubscriptionDashboard,
  payment: SubscriptionPaymentHistoryEntry
) {
  const pdf = buildSimplePdf([
    "PEEPLIFY Invoice",
    dashboard.currentPlan.vendorName,
    `Property code: ${dashboard.currentPlan.propertyCode}`,
    "",
    `Invoice reference: ${payment.cashfreeOrderId ?? payment.checkoutSessionId}`,
    `Plan: ${payment.planLabel}`,
    `Billing cycle: ${payment.billingCycle}`,
    `Employees included: ${payment.employeeLimit ?? "Custom"}`,
    `Branches included: ${payment.branchLimit}`,
    `Access type: ${payment.accessMode}`,
    `Amount paid: ${formatMoney(payment.amount)}`,
    `Payment status: ${payment.paymentStatus ?? "Pending"}`,
    `Created at: ${formatDateTime(payment.createdAt)}`,
    `Verified at: ${formatDateTime(payment.verifiedAt)}`,
    `Access valid until: ${formatDateTime(payment.accessExpiresAt)}`,
    "",
    "Generated by PEEPLIFY subscription billing."
  ]);

  const blob = new Blob([pdf], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `peeplify-invoice-${(payment.cashfreeOrderId ?? payment.checkoutSessionId).toLowerCase()}.pdf`;
  anchor.click();
  URL.revokeObjectURL(url);
}
